services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ums-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - ums-network
    ports:
      - "9000:9000"
    env_file:
      - ./.env

  mysql:
    image: mysql:8.0
    container_name: ums-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ums-network
    ports:
      - "3308:3306"

  nginx:
    image: nginx:alpine
    container_name: ums-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - ums-network

networks:
  ums-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
